### ISSUE TITLE
[TODO] more examples

### ISSUE THREAD

**Issue by inflectrix** [inflectrix/genetic-rs#1]
currently only have readme.rs, should add more later.

**Comment by HyperCodec** [comment]
While there are a few more examples now, I still don't think this is enough. A good example should be complex enough to distinguish statewise entity structs and hereditary information while retaining a link between those in a complex ecosystem.

**Comment by inflectrix** [comment]
I believe this issue will be valid forever as new features are introduced, and for that reason I will close it, as it is something that will be addressed passively with each coming update.
