### ISSUE TITLE
[TODO] potential built-in NEAT implementation?

### ISSUE THREAD

**Issue by inflectrix** [inflectrix/genetic-rs#6]

**Comment by HyperCodec** [comment]
If I end up doing this, will prob use something like DFDX for shape-checking and add it as a feature.

**Comment by HyperCodec** [comment]
I'll begin implementing this, but if it seems too specific or doesn't use a very good API structure, I'll ditch it and close this issue.

**Comment by inflectrix** [comment]
DFDX won't work, will have to write from scratch

**Comment by inflectrix** [comment]
moving to different crate
